services:
  web:
    build: .
    container_name: my-app-production
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.production
    restart: unless-stopped